flask-databases/part 3_refactored/myproject/models.py
# models.py
# setup db inside the __init__.py file
from myproject import db 

class Puppy(db.Model):
    __tablename__ = 'puppies'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner',
                            backref='puppy',
                            uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name: {self.name} and its owner is {self.owner.name}. ID: {self.id}"
        else:
            return f"Puppy name is {self.name} and has no owner. ID: {self.id}"
    
class Owner(db.Model):
    __tablename__ = 'owners'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id    

    def __repr__(self):
        return f"Owner name: {self.name}"

flask-databases/part 3_refactored/myproject/owners/forms.py
# forms.py @ owners
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField("Name of the Owner:")
    puppy_id = IntegerField("ID of Puppy:")
    submit = SubmitField("Add owner")

flask-databases/part 3_refactored/myproject/puppies/forms.py
# forms.py @ puppies
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField("Name of Puppy:")
    submit = SubmitField("Add Puppy")

class DelForm(FlaskForm):
    id = IntegerField("Id number of Puppy to remove:")
    submit = SubmitField("Remove Puppy")

flask-databases/part 3_refactored/myproject/__init__.py
# __init__.py
import os

from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


# Application config
app = Flask(__name__,
            static_folder='/static')

basedir = os.path.abspath(os.path.dirname(__file__))
app.config.from_object(Config)
app.config['SECRET_KEY'] = 'mykey'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Database config
db = SQLAlchemy(app)
Migrate(app, db)

# Blueprints config
from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(puppies_blueprint, url_prefix='/puppies')
app.register_blueprint(owners_blueprint, url_prefix='/owners')

flask-databases/part 3_refactored/myproject/owners/views.py
# views.py @ owners
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprint =Blueprint('owners', 
                            __name__, 
                            template_folder='templates/owners')

@owners_blueprint.route('/add', methods=["GET", "POST"])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        puppy_id = form.puppy_id.data

        new_owner = Owner(name, puppy_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add_owner.html', form=form)

flask-databases/part 3_refactored/myproject/puppies/views.py
# views.py @ puppies
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.puppies.forms import AddForm, DelForm
from myproject.models import Puppy

puppies_blueprint = Blueprint('puppies', __name__,
                              template_folder='templates/puppies')

@puppies_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        # Geet the puppy name from the form
        name = form.name.data
        # Get the object
        new_pup = Puppy(name)
        # Add it to the database
        db.session.add(new_pup)
        db.session.commit()
        # Redirect to list.html to check if it was added
        return redirect(url_for('puppies.list'))
    
    return render_template('add.html', form=form)

@puppies_blueprint.route('/list')
def list():
    # Retrieve all of the puppies
    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)

@puppies_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():    
    form = DelForm()

    if form.validate_on_submit():
        # Geet the puppy data
        id = form.id.data
        pup = Puppy.query.get(id)
        # Delete puppy from database
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))
    
    return render_template('delete.html', form=form)

flask-databases/part 3_refactored/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <style ></style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Adoption Site for Puppies!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('puppies.add') }}">Add Puppy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('puppies.list') }}">List Puppies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('puppies.delete') }}">Delete Puppy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('owners.add') }}">Add owner</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>

flask-databases/part 3_refactored/myproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome!</h1>
    <p>Please select one of the links from the navbar</p>
{% endblock %}